{
 "title": "ROCm Graphs",
 "description": "ROCm Graphics cards",
 "tags": [
  "AMD",
  "ROCm"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "Hostname",
    "query": "SHOW TAG VALUES FROM \"rocm_smi\" WITH KEY = \"host\""
   },
   {
    "name": "GPU",
    "label": "GPU",
    "query": "SHOW TAG VALUES FROM \"rocm_smi\" WITH KEY = \"name\" WHERE host =~ /$hostname/"
   }
  ]
 },
 "panels": [
  { "title": "Current Overview: $GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "GPU" },
  {
   "title": "GPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU VRAM Utilization",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "query": "SELECT (sum(\"memory_used\")/sum(\"memory_total\")*100) FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU VRAM Used",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Fan Speed",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Power Draw",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "power_draw" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Sensor Memory Temprature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "temperature_sensor_memory" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Sensor Edge Temprature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "temperature_sensor_edge" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Sensor Junction Temprature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "temperature_sensor_junction" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "description": "GPU Streaming Multiprocessors clocks",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "clocks_current_sm" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "clocks_current_memory" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "GPU Utilization for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "utilization_gpu" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Memory Utilization for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "query": "SELECT (sum(\"memory_used\") / sum(\"memory_total\"))*100 FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "alias": "Memory Clock  for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "query": "SELECT distinct(\"clocks_current_memory\") FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_memory" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory_Clocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "MHz" }
   ],
   "targets": [
    {
     "alias": "Memory Clock  for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "query": "SELECT distinct(\"clocks_current_sm\") FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "clocks_current_memory" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Fan Speed % for  $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "fan_speed" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU VRAM Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Total Memory for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "memory_total" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    },
    {
     "alias": "Used Memory for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "memory_used" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Sensor Edge  for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "query": "SELECT distinct(\"temperature_sensor_edge\") FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "temperature_sensor_edge" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    },
    {
     "alias": "Sensor Junction  for $GPU on $hostname",
     "query": "SELECT distinct(\"temperature_sensor_junction\") FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    },
    {
     "alias": "Sensor Memory  for $GPU on $hostname",
     "query": "SELECT distinct(\"temperature_sensor_memory\") FROM \"rocm_smi\" WHERE (\"host\" =~ /^$hostname$/ AND \"name\" =~ /^$GPU$/) AND $timeFilter GROUP BY time($__interval) fill(null)"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "Power Draw for $GPU on $hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "rocm_smi",
     "select": [
      [
       { "params": [ "power_draw" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$hostname$/" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$GPU$/" }
     ]
    }
   ]
  },
  { "title": "Graphs $GPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 123 }, "repeat": "GPU" }
 ]
}